version: 0.2

phases:
  install:
    commands:
      - npm i
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/*
    - package.json
    - package-lock.json
  name: api-auth-$(date +%Y%m%d-%H%M%S).zip
cache:
  paths:
    - node_modules
